// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0E0XpbyzEiozMZNEz-WHr4k60Sq9i9YI',
    appId: '1:710187779682:web:f4f6db8645f34519c2733b',
    messagingSenderId: '710187779682',
    projectId: 'request-live-4864a',
    authDomain: 'request-live-4864a.firebaseapp.com',
    storageBucket: 'request-live-4864a.appspot.com',
    measurementId: 'G-WK2JSWGY1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGZpEFdUbKIDBNnm0g1R_y4eCK3dMOws4',
    appId: '1:710187779682:android:e2b168eb862178f7c2733b',
    messagingSenderId: '710187779682',
    projectId: 'request-live-4864a',
    storageBucket: 'request-live-4864a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgC3l30cOfaSG0JiEi7XheSnF2FYGNe1E',
    appId: '1:710187779682:ios:433bc5539a55fba0c2733b',
    messagingSenderId: '710187779682',
    projectId: 'request-live-4864a',
    storageBucket: 'request-live-4864a.appspot.com',
    iosClientId: '710187779682-rjrg3mdcm84gaif6nko0830h8f1u9r8u.apps.googleusercontent.com',
    iosBundleId: 'c',
  );
}
